name: Hello CI
on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Hello
        run: echo Hello, world!

      - name: Data UTC
        run: |
          echo "UTC: $(date -u '+%Y-%m-%d %H:%M:%S')"

      - name: Autor do push
        run: echo "Autor do push: ${{ github.actor }}"
